### PR TITLE
Matrices and their decomposition methods

### PR DESCRIPTION
**Pull request by syedalimohsinbukhari**
# TODO:
- [x] Matrices
  - [x] Add
  - [x] Mul
  - [x] Sub
  - [x] Div
  - [x] Inverse
    - ~Inverse using SVD~ ❌
  - [x] Determinant
  - [x] Transpose
  - [x] Others
- [x] Cholesky decomposition
- [x] LU  
- [x] QR
  - [x] Decomposition
  - [x] Eigen Values using QR 
- [x] Householder transformations 
- [x] Steep-descent
  - [x] Steepest descent
  - [x] Modified steepest descent
- [x] Eigen Values  | 2x2 done
- [x] Eigen decomposition | 2x2 done
- [x] Singular Value Decomposition
    - [x] working for `mxn` where `m=n`
    - [x] SVD working for `mxn` where `m=n-1` or `m=n+1`
    - ~General SVD~ ❌
- [x] Gauss Elimination 
- [x] doc-strings

### CODE REVIEW

**Comment by syedalimohsinbukhari** [comment]
Check if matrix class can only be used as an internal class, this might work by transforming the inputs into matrices internally rather than asking for matrix objects themselves directly.

- The input should be a matrix (list of list of floats)
- The solution should be a single list that can be transformed into a column matrix by transposing it.
- Same with the initial guess, it will be a list of initial guesses that'll be transposed internally.

This will allow to have the Matrix class as an internal back end class. For external exposure, a `matrix` class can be tried that implements nothing extra, everything should be implemented in the `Matrix` class.

**Review by AstrophysicsAndPython — COMMENTED** [review]
Good Work.

**Comment by syedalimohsinbukhari** [comment]
Added partial SVD working for `mxn; m=n and m=n+/-1`

**Comment by syedalimohsinbukhari** [comment]
## Future work
* General SVD
* General EigenValue and EigenVector code

**Pull request merged**
